name: kong
version: '0.1'
summary: Microservice API gateway
description: |
  Microservice API gateway

grade: stable
confinement: strict

apps:
  kong:
    command: bin/kong-wrapper.sh
    plugs:
      - network-bind

parts:
  scripts:
    source: .
    plugin: dump
    prime:
      - config/kong.snap.conf
      - bin/kong-wrapper.sh
  openresty:
    plugin: autotools
    source: https://openresty.org/download/openresty-1.11.2.5.tar.gz
    install-via: prefix
    # configure options here from https://getkong.org/install/source/
    configflags:
      - --with-pcre-jit
      - --with-ipv6
      - --with-http_realip_module
      - --with-http_ssl_module
      - --with-http_stub_status_module
      - --with-http_v2_module
    build-packages: 
      - build-essential
      - libpcre3-dev
      - perl
      - curl
      - libssl-dev
    stage-packages:
      - perl
    override-build: |
      snapcraftctl build
      # openresty will make an absolute symbolic link of openresty to the nginx binary, so we need to clean that up to be relative
      cd $SNAPCRAFT_PART_INSTALL/bin
      rm -rf openresty
      ln -s ../nginx/sbin/nginx openresty
      ln -s ../nginx/sbin/nginx nginx
  luasec:
    after: [luarocks]
    source: https://github.com/limadm/luasec.git
    source-tag: luasec-0.6
    source-depth: 1
    plugin: nil
    build-packages:
      - libssl-dev
    override-build: |
      export ARCH=$(arch)
      echo "running on $ARCH"
      if [ $ARCH = "x86_64" ] || [ $ARCH = "i386" ] ; then
        luarocks make --tree=$SNAPCRAFT_STAGE
      elif [ $ARCH = "armhf" ] ; then
        luarocks make --tree=$SNAPCRAFT_STAGE OPENSSL_LIBDIR=/usr/lib/arm-linux-gnueabihf OPENSSL_INCDIR=/usr/include/
      elif [ $ARCH = "aarch64" ] ; then
        luarocks make --tree=$SNAPCRAFT_STAGE OPENSSL_LIBDIR=/usr/lib/aarch64-linux-gnu OPENSSL_INCDIR=/usr/include/
      fi

  luarocks:
    plugin: nil
    override-build: |
      apt update && apt install -y -qq luarocks
  kong:
    after: 
      - openresty
      - luarocks
      - luasec
    source: https://github.com/kong/kong.git  
    plugin: nil
    source-tag: 0.13.1
    source-depth: 1
    build-packages: 
      - unzip
      - libssl-dev
      - libpcre3-dev
    stage-packages:
      - luarocks
    override-build: |
      

      export ARCH=`arch`
      if [ $ARCH = "x86_64" ] || [ $ARCH = "i386" ] ; then
        luarocks install --tree=$SNAPCRAFT_STAGE kong 0.13.1-0
      elif [ $ARCH = "armhf" ] ; then
        luarocks install --tree=$SNAPCRAFT_STAGE kong 0.13.1-0 OPENSSL_LIBDIR=/usr/lib/arm-linux-gnueabihf OPENSSL_INCDIR=/usr/include/
      elif [ $ARCH = "aarch64" ] ; then
        luarocks install --tree=$SNAPCRAFT_STAGE kong 0.13.1-0 OPENSSL_LIBDIR=/usr/lib/aarch64-linux-gnu OPENSSL_INCDIR=/usr/include/
      fi
      
      mkdir -p $SNAPCRAFT_STAGE/bin
      cp bin/kong $SNAPCRAFT_STAGE/bin/kong
      # make all the things inside the cmd directory executable because they for some reason aren't executable by default...
      cd $SNAPCRAFT_STAGE/share/lua/5.1/kong/cmd
      for cmd in $(ls *.lua); do
        chmod +x $cmd
      done
