name: kong
version: '0.13.1'
summary: The Cloud-Native API Gateway
description: |
  Kong is a cloud-native, fast, scalable, and distributed Microservice Abstraction Layer 
  (also known as an API Gateway, API Middleware or in some cases Service Mesh). Made 
  available as an open-source project in 2015, its core values are high performance and extensibility.


grade: stable
confinement: strict

apps:
  kong:
    command: bin/kong-wrapper.sh
    plugs:
      - network-bind
      - network

parts:
  scripts:
    source: .
    plugin: dump
    prime:
      - config/kong.snap.conf
      - bin/kong-wrapper.sh
  openresty:
    plugin: autotools
    source: https://openresty.org/download/openresty-1.11.2.5.tar.gz
    install-via: prefix
    # configure options here from https://getkong.org/install/source/
    configflags:
      - --with-pcre-jit
      - --with-ipv6
      - --with-http_realip_module
      - --with-http_ssl_module
      - --with-http_stub_status_module
      - --with-http_v2_module
    build-packages: 
      - build-essential
      - libpcre3-dev
      - perl
      - curl
      - libssl-dev
    stage-packages:
      - perl
  luarocks:
    after: [lua]
    plugin: autotools
    source: https://github.com/luarocks/luarocks.git
    source-branch: 2.4.3
    source-depth: 1
    override-build: |
      ./configure --prefix=$SNAPCRAFT_STAGE --with-lua=$SNAPCRAFT_STAGE --lua-version=5.1
      make build
      make install
  lua:
    source: https://www.lua.org/ftp/lua-5.1.5.tar.gz
    source-type: tar
    plugin: make
    make-parameters: [linux]
    build-packages:
      - libreadline-dev
      - libncurses5-dev
    override-build: |
      # patch the Makefile to use $SNAPCRAFT_STAGE for the INSTALL_TOP variable
      # which unfortunately is not settable using an environment variable and thus needs 
      # this manual patch
      sed -i "s@INSTALL_TOP= /usr/local@INSTALL_TOP=$SNAPCRAFT_STAGE@" Makefile
      snapcraftctl build
  kong:
    after: 
      - openresty
      - luarocks
    source: https://github.com/kong/kong.git  
    plugin: nil
    source-tag: 0.13.1
    source-depth: 1
    build-packages: 
      - unzip
      - libssl-dev
      - libpcre3-dev
    stage-packages:
      - luarocks
    override-build: |
      # handle the location of openssl + libcrypto by architecture
      # cause luarocks is silly and hardcodes /usr/lib/x86_64-linux-gnu as the lib search path
      ARCH=$(uname -m)
      case $ARCH in
      aarch64*)
        luarocks make --tree=$SNAPCRAFT_STAGE \
          CRYPTO_LIBDIR=/usr/lib/aarch64-linux-gnu \
          CRYPTO_INCDIR=/usr/include \
          OPENSSL_LIBDIR=/usr/lib/aarch64-linux-gnu \
          OPENSSL_INCDIR=/usr/include
        ;;
      arm*)
        luarocks make --tree=$SNAPCRAFT_STAGE \
          CRYPTO_LIBDIR=/usr/lib/arm-linux-gnueabihf \
          CRYPTO_INCDIR=/usr/include \
          OPENSSL_LIBDIR=/usr/lib/arm-linux-gnueabihf \
          OPENSSL_INCDIR=/usr/include
        ;;
      i386|i686)
        luarocks make --tree=$SNAPCRAFT_STAGE \
          CRYPTO_LIBDIR=/usr/lib/i386-linux-gnu \
          CRYPTO_INCDIR=/usr/include \
          OPENSSL_LIBDIR=/usr/lib/i386-linux-gnu \
          OPENSSL_INCDIR=/usr/include
        ;;
      x86_64)
        # x64 is the only arch that luarocks can properly find libs for :-/
        luarocks make --tree=$SNAPCRAFT_STAGE
        ;;
      *)
        echo "Unsupported arch $ARCH"
        exit 1
        ;;
      esac
      
      mkdir -p $SNAPCRAFT_STAGE/bin
      cp bin/kong $SNAPCRAFT_STAGE/bin/kong
      # make all the things inside the cmd directory executable because they for some reason aren't executable by default...
      cd $SNAPCRAFT_STAGE/share/lua/5.1/kong/cmd
      for cmd in $(ls *.lua); do
        chmod +x $cmd
      done

      # install everything from stage into the part install for kong
      cp -r $SNAPCRAFT_STAGE/* $SNAPCRAFT_PART_INSTALL/

      # openresty will make an absolute symbolic link of openresty to the nginx binary, so we need to delete that
      # note that the reason we do this in the kong part rather than the openresty is that kong will create it's own
      # absolute symlink, so we want to delete that one too, and doing that here fixes both openresty's symlink as well
      # as kong's
      cd $SNAPCRAFT_STAGE/bin
      rm -rf openresty
      ln -s ../nginx/sbin/nginx openresty
      ln -s ../nginx/sbin/nginx nginx
