name: kong
version: '0.1'
summary: Microservice API gateway
description: |
  Microservice API gateway

grade: devel
confinement: devmode

apps:
  kong:
    command: bin/kong
    plugs:
      - network-bind

parts:
  openresty:
    plugin: autotools
    install-via: prefix
    # configure options here from https://getkong.org/install/source/
    configflags:
      - --with-pcre-jit
      - --with-ipv6
      - --with-http_realip_module
      - --with-http_ssl_module
      - --with-http_stub_status_module
      - --with-http_v2_module
    build-packages: 
      - build-essential
      - libpcre3-dev
      - perl
      - curl
      - libssl-dev
    stage-packages:
      - perl
      - libfindbin-libs-perl
    source: https://openresty.org/download/openresty-1.11.2.5.tar.gz
    override-build: |
      # do normal build and copy it into stage
      snapcraftctl build
      # openresty will make an absolute symbolic link of openresty to the nginx binary, so we need to clean that up to be relative
      cd $SNAPCRAFT_PART_INSTALL/bin
      rm -rf openresty
      ln -s ../nginx/sbin/nginx openresty
  kong:
    after: [openresty]
    source: https://github.com/kong/kong.git  
    plugin: nil
    source-tag: 0.13.1
    source-depth: 1
    stage-packages:
      - luarocks
      - libfindbin-libs-perl
    build-packages: 
      - unzip
      - luarocks
    override-build: |
      luarocks install --tree=$SNAPCRAFT_PART_INSTALL kong 0.13.1-0
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp bin/kong $SNAPCRAFT_PART_INSTALL/bin/kong
