name: kong
version: '0.1'
summary: Microservice API gateway
description: |
  Microservice API gateway

grade: devel
confinement: devmode

apps:
  kong:
    command: bin/kong
    environment:
      PERL5LIB: ${SNAP}/usr/local/lib/x86_64-linux-gnu/perl/5.22.1:${SNAP}/usr/local/share/perl/5.22.1:${SNAP}/usr/lib/x86_64-linux-gnu/perl5/5.22:${SNAP}/usr/share/perl5:${SNAP}/usr/lib/x86_64-linux-gnu/perl/5.22:${SNAP}/usr/share/perl/5.22:${SNAP}/usr/local/lib/site_perl:${SNAP}/usr/lib/x86_64-linux-gnu/perl-base
      LD_LIBRARY_PATH: ${LD_LIBRARY_PATH}:${SNAP}/luajit/lib
      LUA_PATH: ${SNAP}/lualib/?.lua;${SNAP}/usr/share/lua/5.1/?.lua;${SNAP}/usr/share/lua/5.1/luarocks/?.lua;;
    plugs:
      - network-bind

parts:
  config:
    source: .
    plugin: dump
    prime:
      - config/kong.snap.conf
  openresty:
    plugin: autotools
    source: https://openresty.org/download/openresty-1.11.2.5.tar.gz
    install-via: prefix
    # configure options here from https://getkong.org/install/source/
    configflags:
      - --with-pcre-jit
      - --with-ipv6
      - --with-http_realip_module
      - --with-http_ssl_module
      - --with-http_stub_status_module
      - --with-http_v2_module
    build-packages: 
      - build-essential
      - libpcre3-dev
      - perl
      - curl
      - libssl-dev
    stage-packages:
      - perl
    override-build: |
      snapcraftctl build
      # openresty will make an absolute symbolic link of openresty to the nginx binary, so we need to clean that up to be relative
      cd $SNAPCRAFT_PART_INSTALL/bin
      rm -rf openresty
      ln -s ../nginx/sbin/nginx openresty
  kong:
    after: [openresty]
    source: https://github.com/kong/kong.git  
    plugin: nil
    source-tag: 0.13.1
    source-depth: 1
    build-packages: 
      - unzip
      - luarocks
    stage-packages:
      - luarocks
    override-build: |
      luarocks install --tree=$SNAPCRAFT_PART_INSTALL kong 0.13.1-0
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp bin/kong $SNAPCRAFT_PART_INSTALL/bin/kong
