name: Snap
on: [push, pull_request]
jobs:
  build-snap:
    name: Snap building
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build the snap
        uses: snapcore/action-build@v1
      - name: Uploading snap artifact
        uses: actions/upload-artifact@v2
        with:
          name: snap-files
          path: "*.snap"
  test-snap:
    runs-on: ubuntu-latest
    needs: build-snap
    steps:
      - name: Download built snap
        uses: actions/download-artifact@v2
        with:
          name: snap-files
      - name: Install Built snap
        shell: bash
        run: sudo snap install --dangerous kong*.snap
      - name: Verify snap services
        shell: bash
        run: |
          # wait a bit to make sure that we can ping kong
          sleep 10
          snap services kong | grep kong-daemon | grep -P "enabled\s+active"
          snap services kong | grep postgres | grep -P "enabled\s+active"
          sudo kong health --prefix /var/snap/kong/current
