#!/bin/bash -e

# check if the config file exists
if [ ! -f "$SNAP_COMMON/config/kong.conf" ]; then
    mkdir -p $SNAP_COMMON/config
    cp $SNAP/config/kong.snap.conf $SNAP_COMMON/config/kong.conf
fi
